#!/usr/bin/env python3
"""86 production tokens with full 6-month + 30-day historical data."""

PRODUCTION_SYMBOLS = [
    "1000BONKUSDT", "1000FLOKIUSDT", "1000LUNCUSDT", "1000PEPEUSDT", "1000SATSUSDT", "1000SHIBUSDT",
    "AAVEUSDT", "ACHUSDT", "ADAUSDT", "ALGOUSDT", "AMPUSDT", "APTUSDT", "ARBUSDT", "ARDRUSDT", "ATOMUSDT",
    "AVAXUSDT", "AXSUSDT", "BATUSDT", "BCHUSDT", "BLURUSDT", "BNBUSDT", "BOMEUSDT", "BONKUSDT", "BTCUSDT",
    "C98USDT", "CFXUSDT", "CHZUSDT", "COMPUSDT", "DASHUSDT", "DOGEUSDT", "DOTUSDT", "DYDXUSDT", "DYMUSDT",
    "EGLDUSDT", "EIGENUSDT", "ENAUSDT", "ENJUSDT", "ENSUSDT", "ETCUSDT", "ETHUSDT", "FETUSDT", "FILUSDT",
    "FLOKIUSDT", "FLOWUSDT", "GALAUSDT", "HBARUSDT", "ICPUSDT", "IMXUSDT", "INJUSDT", "JASMYUSDT",
    "JUPUSDT", "KASUSDT", "LDOUSDT", "LINKUSDT", "LPTUSDT", "LTCUSDT", "MANAUSDT", "MEMEUSDT", "MKRUSDT",
    "NEARUSDT", "NEOUSDT", "NTRNUSDT", "ONEUSDT", "OPUSDT", "ORDIUSDT", "PEOPLEUSDT", "PEPEUSDT", "PIXELUSDT",
    "PORTALUSDT", "PYTHUSDT", "QNTUSDT", "RAYUSDT", "RSRUSDT", "RVNUSDT", "SANDUSDT", "SEIUSDT", "SFPUSDT",
    "SHIBUSDT", "SOLUSDT", "STPTUSDT", "STXUSDT", "SUIUSDT", "SUSHIUSDT", "TAOUSDT", "THETAUSDT", "TIAUSDT",
    "TRBUSDT", "TRUMPUSDT", "TRXUSDT", "TURBOUSDT", "UNIUSDT", "VETUSDT", "VIRTUALUSDT", "WIFUSDT", "WLDUSDT",
    "XLMUSDT", "XMRUSDT", "XRPUSDT", "ZECUSDT", "ZILUSDT", "ZKUSDT"
]

if __name__ == "__main__":
    print(f"Production tokens: {len(PRODUCTION_SYMBOLS)}")
    print(f"Expected models: {len(PRODUCTION_SYMBOLS) * 2} (long+short)")
    print("Ready for AAA-grade training!")
